// API Constants
export const API_BASE_URL =
  process.env.REACT_APP_API_URL || "http://localhost:5000/api/v1";

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: `/auth/login`,
    REGISTER: `/auth/register`,
    LOGOUT: `/auth/logout`,
    REFRESH: `/auth/refresh`,
    VERIFY_EMAIL: `/auth/verify-email`,
    FORGOT_PASSWORD: `/auth/forgot-password`,
    RESET_PASSWORD: `/auth/reset-password`,
    CHANGE_PASSWORD: `/auth/change-password`,
    VERIFY: `/auth/verify`,
    RESEND_VERIFICATION: `/auth/resend-verification`,
  },
  USER: {
    PROFILE: `/user/profile`,
    UPDATE_PROFILE: `/user/profile`,
    UPLOAD_RESUME: `/user/resume`,
    GET_JOBS: `/user/jobs`,
    SAVED_JOBS: `/user/saved-jobs`,
    APPLICATION_HISTORY: `/user/applications`,
    SETTINGS: `/user/settings`,
    DASHBOARD_STATS: `/user/dashboard`,
    ONBOARDING: `/user/onboarding`,
  },
  ADMIN: {
    DASHBOARD: `/admin/dashboard`,
    USERS: `/admin/users`,
    APPLICATIONS: `/admin/applications`,
    JOBS: `/admin/jobs`,
    ANALYTICS: `/admin/analytics`,
    SYSTEM_SETTINGS: `/admin/settings`,
  },
  AI: {
    EXTRACT_TEXT: `/ai/extract-text`,
    PARSE_RESUME: `/ai/parse-resume`,
    ENHANCE_RESUME: `/ai/enhance-resume`,
    ANALYZE_JOB_MATCH: `/ai/analyze-job-match`,
    STATUS: `/ai/status`,
  },
  JOBS: {
    SEARCH: `/jobs/search`,
    DETAILS: `/jobs/:id`,
    APPLY: `/jobs/:id/apply`,
    SCRAPED_JOBS: `/jobs/scraped`,
  },
  APPLICATIONS: {
    CREATE: `/applications`,
    GET_ALL: `/applications`,
    GET_BY_ID: `/applications/:id`,
    UPDATE_STATUS: `/applications/:id/status`,
  },
};

// Application Routes (same as API endpoints structure for frontend routing)
export const ROUTES = {
  HOME: "/",
  AUTH: "/auth",
  ONBOARDING: "/onboarding",
  PAYMENT: "/payment",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  JOBS: "/jobs",
  TOOLS: "/tools",
  SETTINGS: "/settings",
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    APPLICANTS: "/admin/applicants",
    APPLICATIONS: "/admin/applications",
    ANALYTICS: "/admin/analytics",
  },
};

// User Types
export const USER_TYPES = {
  JOB_SEEKER: "job_seeker",
  ADMIN: "admin",
};

// Onboarding Steps
export const ONBOARDING_STEPS = {
  BASIC_INFO: "basic_info",
  RESUME_UPLOAD: "resume_upload",
  JOB_PREFERENCES: "job_preferences",
};

// Experience Levels
export const EXPERIENCE_LEVELS = [
  { value: "0-1", label: "Entry Level (0-1 years)" },
  { value: "1-3", label: "Junior (1-3 years)" },
  { value: "3-5", label: "Mid-level (3-5 years)" },
  { value: "5-10", label: "Senior (5-10 years)" },
  { value: "10+", label: "Expert (10+ years)" },
];

// Education Levels
export const EDUCATION_LEVELS = [
  { value: "high_school", label: "High School" },
  { value: "associate", label: "Associate Degree" },
  { value: "bachelor", label: "Bachelor's Degree" },
  { value: "master", label: "Master's Degree" },
  { value: "phd", label: "PhD" },
  { value: "other", label: "Other" },
];

// Job Types
export const JOB_TYPES = [
  { value: "full_time", label: "Full Time" },
  { value: "part_time", label: "Part Time" },
  { value: "contract", label: "Contract" },
  { value: "freelance", label: "Freelance" },
  { value: "internship", label: "Internship" },
];

// Work Types
export const WORK_TYPES = [
  { value: "remote", label: "Remote" },
  { value: "hybrid", label: "Hybrid" },
  { value: "onsite", label: "On-site" },
];

// Application Status
export const APPLICATION_STATUS = {
  PENDING: "pending",
  APPLIED: "applied",
  REVIEWING: "reviewing",
  INTERVIEWING: "interviewing",
  REJECTED: "rejected",
  ACCEPTED: "accepted",
  WITHDRAWN: "withdrawn",
};

// AI Status Constants - ADDED THIS!
export const AI_STATUS = {
  NOT_CONFIGURED: "not_configured",
  OPERATIONAL: "operational",
  INVALID_KEY: "invalid_key",
  ERROR: "error",
  UNAVAILABLE: "unavailable",
};

// Local Storage Keys
export const STORAGE_KEYS = {
  AUTH_TOKEN: "auth_token",
  REFRESH_TOKEN: "refresh_token",
  USER_DATA: "user_data",
  THEME: "theme",
  LANGUAGE: "language",
  ONBOARDING_PROGRESS: "onboarding_progress",
};

// File Upload Constants
export const FILE_UPLOAD = {
  MAX_SIZE: 5 * 1024 * 1024, // 5MB
  ALLOWED_TYPES: [
    "application/pdf",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  ],
  ALLOWED_EXTENSIONS: [".pdf", ".doc", ".docx"],
};

// Industries
export const INDUSTRIES = [
  { value: "technology", label: "Technology" },
  { value: "healthcare", label: "Healthcare & Medical" },
  { value: "finance", label: "Finance & Banking" },
  { value: "education", label: "Education" },
  { value: "retail", label: "Retail & E-commerce" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "construction", label: "Construction & Real Estate" },
  { value: "consulting", label: "Consulting" },
  { value: "media", label: "Media & Entertainment" },
  { value: "government", label: "Government & Public Sector" },
  { value: "nonprofit", label: "Non-profit" },
  { value: "automotive", label: "Automotive" },
  { value: "aerospace", label: "Aerospace & Defense" },
  { value: "energy", label: "Energy & Utilities" },
  { value: "telecommunications", label: "Telecommunications" },
  { value: "transportation", label: "Transportation & Logistics" },
  { value: "hospitality", label: "Hospitality & Tourism" },
  { value: "agriculture", label: "Agriculture & Food" },
  { value: "legal", label: "Legal Services" },
  { value: "insurance", label: "Insurance" },
  { value: "pharmaceuticals", label: "Pharmaceuticals" },
  { value: "biotechnology", label: "Biotechnology" },
  { value: "chemicals", label: "Chemicals" },
  { value: "mining", label: "Mining & Metals" },
  { value: "textiles", label: "Textiles & Apparel" },
  { value: "sports", label: "Sports & Recreation" },
  { value: "arts", label: "Arts & Culture" },
  { value: "environmental", label: "Environmental Services" },
  { value: "security", label: "Security Services" },
  { value: "other", label: "Other" },
];

// Common Skills
export const SKILLS = [
  // Programming Languages
  "JavaScript", "Python", "Java", "C++", "C#", "PHP", "Ruby", "Go", "Rust",
  "Swift", "Kotlin", "TypeScript", "Scala", "R", "MATLAB", "Perl", "Dart",
  "Objective-C", "Assembly", "COBOL", "Fortran", "Haskell", "Clojure",
  "Erlang", "F#", "VB.NET", "PowerShell", "Bash", "Shell Scripting",

  // Web Technologies
  "HTML", "CSS", "React", "Vue.js", "Angular", "Node.js", "Express.js",
  "Next.js", "Nuxt.js", "Svelte", "jQuery", "Bootstrap", "Tailwind CSS",
  "SASS/SCSS", "Less", "Webpack", "Vite", "Gulp", "Grunt", "Babel",

  // Databases
  "MySQL", "PostgreSQL", "MongoDB", "Redis", "SQLite", "Oracle",
  "Microsoft SQL Server", "MariaDB", "Cassandra", "DynamoDB", "Neo4j",
  "InfluxDB", "CouchDB", "Firebase", "Supabase",

  // Cloud & DevOps
  "AWS", "Azure", "Google Cloud Platform", "Docker", "Kubernetes",
  "Jenkins", "GitLab CI/CD", "GitHub Actions", "Terraform", "Ansible",
  "Chef", "Puppet", "Vagrant", "Nginx", "Apache", "Linux", "Ubuntu",
  "CentOS", "RedHat", "Windows Server",

  // Mobile Development
  "React Native", "Flutter", "iOS Development", "Android Development",
  "Xamarin", "Ionic", "Cordova", "Unity", "Unreal Engine",

  // Data & Analytics
  "SQL", "Data Analysis", "Machine Learning", "AI", "Deep Learning",
  "TensorFlow", "PyTorch", "Keras", "Scikit-learn", "Pandas", "NumPy",
  "Apache Spark", "Hadoop", "Tableau", "Power BI", "Excel", "SPSS",
  "SAS", "Apache Kafka", "Elasticsearch", "Kibana", "Grafana",

  // Design & Creative
  "UI/UX Design", "Figma", "Adobe Creative Suite", "Sketch", "Photoshop",
  "Illustrator", "InDesign", "After Effects", "Premiere Pro", "Blender",
  "AutoCAD", "3ds Max", "Maya", "Cinema 4D", "Canva", "Adobe XD",
  "Principle", "Framer", "InVision", "Zeplin",

  // Project Management & Business
  "Agile", "Scrum", "Kanban", "Jira", "Trello", "Asana", "Monday.com",
  "Microsoft Project", "Slack", "Teams", "Zoom", "Project Management",
  "Product Management", "Business Analysis", "Requirements Gathering",
  "Stakeholder Management", "Risk Management", "Quality Assurance",

  // Marketing & Sales
  "Digital Marketing", "SEO", "SEM", "Google Ads", "Facebook Ads",
  "Social Media Marketing", "Content Marketing", "Email Marketing",
  "Marketing Automation", "HubSpot", "Salesforce", "Mailchimp",
  "Google Analytics", "Adobe Analytics", "A/B Testing", "Conversion Optimization",
  "Sales", "Lead Generation", "Customer Relationship Management",
  "Market Research", "Brand Management", "Public Relations",

  // Financial & Accounting
  "Financial Analysis", "Accounting", "Bookkeeping", "Tax Preparation",
  "Auditing", "Financial Modeling", "Investment Analysis", "Risk Assessment",
  "QuickBooks", "SAP", "Excel Financial Modeling", "Bloomberg Terminal",
  "Financial Planning", "Budgeting", "Cost Accounting", "Forensic Accounting",

  // Healthcare & Medical
  "Medical Terminology", "Patient Care", "Electronic Health Records",
  "Medical Coding", "HIPAA Compliance", "Clinical Research", "Pharmacology",
  "Medical Imaging", "Laboratory Procedures", "Nursing Care", "Physical Therapy",
  "Occupational Therapy", "Medical Administration", "Healthcare Management",

  // Legal
  "Legal Research", "Contract Law", "Corporate Law", "Intellectual Property",
  "Litigation", "Compliance", "Legal Writing", "Case Management",
  "Paralegal Skills", "Document Review", "Due Diligence", "Regulatory Affairs",

  // Education & Training
  "Curriculum Development", "Instructional Design", "Educational Technology",
  "Classroom Management", "Student Assessment", "Learning Management Systems",
  "Training Development", "Adult Learning", "Special Education", "ESL Teaching",

  // Manufacturing & Engineering
  "Lean Manufacturing", "Six Sigma", "Quality Control", "Process Improvement",
  "CAD Design", "Product Development", "Supply Chain Management",
  "Operations Management", "Inventory Management", "Safety Management",
  "Mechanical Engineering", "Electrical Engineering", "Civil Engineering",
  "Chemical Engineering", "Industrial Engineering",

  // Soft Skills
  "Communication", "Leadership", "Problem Solving", "Team Work",
  "Critical Thinking", "Creativity", "Adaptability", "Time Management",
  "Customer Service", "Presentation Skills", "Negotiation", "Conflict Resolution",
  "Mentoring", "Public Speaking", "Emotional Intelligence", "Strategic Thinking",
  "Decision Making", "Attention to Detail", "Multi-tasking", "Stress Management",

  // Languages
  "English", "Spanish", "French", "German", "Chinese (Mandarin)", "Japanese",
  "Korean", "Arabic", "Portuguese", "Russian", "Italian", "Dutch", "Swedish",
  "Norwegian", "Danish", "Finnish", "Polish", "Hindi", "Bengali", "Tamil",
  "Telugu", "Marathi", "Gujarati", "Urdu", "Thai", "Vietnamese", "Indonesian",
  "Malay", "Turkish", "Greek", "Hebrew", "Czech", "Hungarian", "Romanian",

  // Industry-Specific Skills
  "Real Estate", "Property Management", "Construction Management", "Architecture",
  "Interior Design", "Urban Planning", "Environmental Science", "Renewable Energy",
  "Oil & Gas", "Mining", "Agriculture", "Food Safety", "Hospitality Management",
  "Event Planning", "Travel Planning", "Sports Management", "Fitness Training",
  "Nutrition", "Culinary Arts", "Fashion Design", "Jewelry Design", "Music Production",
  "Video Production", "Photography", "Writing", "Editing", "Translation",
  "Interpretation", "Social Work", "Psychology", "Counseling", "Therapy",
];

// Common Job Titles for suggestions
export const JOB_TITLES = [
  // Technology & IT
  "Software Engineer", "Frontend Developer", "Backend Developer", "Full Stack Developer",
  "Mobile App Developer", "Web Developer", "DevOps Engineer", "Data Scientist",
  "Data Analyst", "Machine Learning Engineer", "AI Engineer", "Cloud Engineer",
  "Cybersecurity Specialist", "Information Security Analyst", "Database Administrator",
  "System Administrator", "Network Engineer", "Network Administrator", "IT Support Specialist",
  "Technical Support Specialist", "Product Manager", "Technical Product Manager",
  "QA Engineer", "Test Automation Engineer", "Quality Assurance Analyst", "UI/UX Designer",
  "User Experience Designer", "User Interface Designer", "Web Designer", "Graphic Designer",
  "Digital Designer", "Technical Writer", "Solutions Architect", "Software Architect",
  "Systems Architect", "Engineering Manager", "Tech Lead", "Senior Software Engineer",
  "Junior Developer", "Intern Developer", "Site Reliability Engineer", "Platform Engineer",
  "Security Engineer", "Penetration Tester", "Ethical Hacker", "IT Director",
  "Chief Technology Officer", "Chief Information Officer", "Scrum Master", "Agile Coach",
  "Business Analyst", "Systems Analyst", "Data Engineer", "Big Data Engineer",
  "Cloud Architect", "Infrastructure Engineer", "Release Manager", "Configuration Manager",

  // Healthcare & Medical
  "Physician", "Doctor", "Surgeon", "Cardiologist", "Neurologist", "Oncologist",
  "Pediatrician", "Psychiatrist", "Radiologist", "Anesthesiologist", "Dermatologist",
  "Orthopedic Surgeon", "Emergency Medicine Physician", "Family Medicine Doctor",
  "Internal Medicine Physician", "Registered Nurse", "Licensed Practical Nurse",
  "Nurse Practitioner", "Certified Nursing Assistant", "Medical Assistant",
  "Physical Therapist", "Occupational Therapist", "Speech Therapist", "Respiratory Therapist",
  "Pharmacist", "Pharmacy Technician", "Medical Technologist", "Laboratory Technician",
  "Radiology Technician", "MRI Technician", "X-Ray Technician", "Ultrasound Technician",
  "Dental Hygienist", "Dentist", "Orthodontist", "Oral Surgeon", "Veterinarian",
  "Veterinary Technician", "Paramedic", "EMT", "Healthcare Administrator",
  "Medical Coder", "Medical Biller", "Medical Records Specialist", "Hospital Administrator",
  "Nursing Home Administrator", "Home Health Aide", "Personal Care Aide",
  "Medical Social Worker", "Clinical Research Coordinator", "Medical Research Scientist",
  "Epidemiologist", "Public Health Specialist", "Health Inspector", "Nutritionist",
  "Dietitian", "Mental Health Counselor", "Clinical Psychologist", "Therapist",
  "Social Worker", "Substance Abuse Counselor", "Marriage and Family Therapist",
  "Art Therapist", "Music Therapist", "Recreation Therapist", "Chiropractor",
  "Podiatrist", "Optometrist", "Audiologist", "Prosthetist", "Orthotist",

  // Finance & Accounting
  "Accountant", "Senior Accountant", "Staff Accountant", "Public Accountant",
  "Management Accountant", "Cost Accountant", "Tax Accountant", "Forensic Accountant",
  "Auditor", "Internal Auditor", "External Auditor", "Tax Auditor", "Bookkeeper",
  "Payroll Specialist", "Accounts Payable Specialist", "Accounts Receivable Specialist",
  "Financial Analyst", "Senior Financial Analyst", "Budget Analyst", "Credit Analyst",
  "Investment Analyst", "Research Analyst", "Equity Analyst", "Fixed Income Analyst",
  "Risk Analyst", "Compliance Analyst", "Financial Planner", "Wealth Manager",
  "Investment Advisor", "Portfolio Manager", "Fund Manager", "Asset Manager",
  "Treasurer", "Controller", "Assistant Controller", "Finance Manager",
  "Accounting Manager", "CFO", "Chief Financial Officer", "Finance Director",
  "Vice President of Finance", "Financial Consultant", "Tax Preparer", "Tax Specialist",
  "Insurance Agent", "Insurance Broker", "Claims Adjuster", "Underwriter",
  "Actuary", "Pension Administrator", "Credit Officer", "Loan Officer",
  "Mortgage Broker", "Investment Banking Analyst", "Investment Banker",
  "Corporate Finance Analyst", "M&A Analyst", "Private Equity Associate",
  "Venture Capital Analyst", "Hedge Fund Analyst", "Trader", "Day Trader",
  "Financial Advisor", "Certified Financial Planner", "Bank Teller", "Bank Manager",
  "Branch Manager", "Commercial Banker", "Relationship Manager",

  // Education & Training
  "Teacher", "Elementary School Teacher", "Middle School Teacher", "High School Teacher",
  "Kindergarten Teacher", "Preschool Teacher", "Special Education Teacher",
  "English Teacher", "Math Teacher", "Science Teacher", "History Teacher",
  "Social Studies Teacher", "Physical Education Teacher", "Music Teacher",
  "Art Teacher", "Foreign Language Teacher", "ESL Teacher", "Reading Specialist",
  "Learning Specialist", "School Counselor", "Guidance Counselor", "School Psychologist",
  "School Social Worker", "Principal", "Assistant Principal", "Vice Principal",
  "Superintendent", "Curriculum Developer", "Instructional Designer", "Education Coordinator",
  "Professor", "Associate Professor", "Assistant Professor", "Adjunct Professor",
  "Research Professor", "Department Chair", "Dean", "Academic Advisor",
  "Admissions Counselor", "Student Affairs Coordinator", "Registrar", "Librarian",
  "School Librarian", "Academic Librarian", "Research Librarian", "Teaching Assistant",
  "Graduate Teaching Assistant", "Research Assistant", "Tutor", "Private Tutor",
  "Online Tutor", "Educational Consultant", "Corporate Trainer", "Training Specialist",
  "Learning and Development Specialist", "Training Coordinator", "Training Manager",
  "Instructional Coordinator", "Education Administrator", "School Administrator",
  "Educational Technology Specialist", "Distance Learning Coordinator",

  // Sales & Marketing
  "Sales Representative", "Sales Associate", "Account Executive", "Senior Account Executive",
  "Account Manager", "Key Account Manager", "Sales Manager", "Regional Sales Manager",
  "National Sales Manager", "Sales Director", "Vice President of Sales",
  "Business Development Representative", "Business Development Manager", "Sales Engineer",
  "Technical Sales Representative", "Inside Sales Representative", "Outside Sales Representative",
  "Territory Sales Manager", "Channel Sales Manager", "Retail Sales Associate",
  "Store Manager", "Assistant Store Manager", "District Manager", "Regional Manager",
  "Customer Success Manager", "Customer Account Manager", "Client Relationship Manager",
  "Sales Coordinator", "Sales Assistant", "Lead Generation Specialist",
  "Marketing Manager", "Senior Marketing Manager", "Marketing Director",
  "Vice President of Marketing", "Chief Marketing Officer", "Brand Manager",
  "Product Marketing Manager", "Content Marketing Manager", "Digital Marketing Manager",
  "Social Media Manager", "Social Media Specialist", "SEO Specialist", "SEM Specialist",
  "PPC Specialist", "Email Marketing Specialist", "Marketing Analyst", "Market Research Analyst",
  "Marketing Coordinator", "Marketing Assistant", "Public Relations Specialist",
  "PR Manager", "Communications Specialist", "Communications Manager",
  "Advertising Account Executive", "Media Planner", "Media Buyer", "Creative Director",
  "Art Director", "Copywriter", "Graphic Designer", "Marketing Designer",
  "Event Marketing Manager", "Trade Show Coordinator", "Growth Hacker",
  "Demand Generation Manager", "Field Marketing Manager", "Partner Marketing Manager",
  "Influencer Marketing Manager", "Affiliate Marketing Manager", "Performance Marketing Manager",

  // Legal & Law Enforcement
  "Lawyer", "Attorney", "Corporate Lawyer", "Criminal Lawyer", "Family Lawyer",
  "Personal Injury Lawyer", "Real Estate Lawyer", "Immigration Lawyer", "Tax Lawyer",
  "Employment Lawyer", "Environmental Lawyer", "Intellectual Property Lawyer",
  "Patent Lawyer", "Trademark Lawyer", "Public Defender", "District Attorney",
  "Prosecutor", "Judge", "Magistrate", "Court Reporter", "Court Clerk",
  "Paralegal", "Legal Assistant", "Legal Secretary", "Law Clerk", "Legal Researcher",
  "Compliance Officer", "Legal Counsel", "In-House Counsel", "General Counsel",
  "Chief Legal Officer", "Contract Manager", "Legal Analyst", "Legal Consultant",
  "Mediator", "Arbitrator", "Notary Public", "Process Server", "Bailiff",
  "Police Officer", "Detective", "Sheriff", "Deputy Sheriff", "State Trooper",
  "Federal Agent", "FBI Agent", "DEA Agent", "Border Patrol Agent", "Immigration Officer",
  "Customs Officer", "Security Guard", "Private Investigator", "Correctional Officer",
  "Probation Officer", "Parole Officer", "Court Security Officer", "Bailiff",
  "Emergency Dispatcher", "911 Operator", "Crime Scene Investigator", "Forensic Scientist",
  "Forensic Analyst", "Criminal Justice Specialist", "Victim Advocate",

  // Engineering & Architecture
  "Civil Engineer", "Mechanical Engineer", "Electrical Engineer", "Chemical Engineer",
  "Aerospace Engineer", "Industrial Engineer", "Environmental Engineer", "Biomedical Engineer",
  "Structural Engineer", "Transportation Engineer", "Geotechnical Engineer", "Water Resources Engineer",
  "Software Engineer", "Computer Engineer", "Systems Engineer", "Design Engineer",
  "Process Engineer", "Quality Engineer", "Safety Engineer", "Reliability Engineer",
  "Project Engineer", "Field Engineer", "Test Engineer", "Research Engineer",
  "Development Engineer", "Manufacturing Engineer", "Production Engineer", "Plant Engineer",
  "Maintenance Engineer", "Facilities Engineer", "Construction Engineer", "Site Engineer",
  "Consulting Engineer", "Chief Engineer", "Principal Engineer", "Senior Engineer",
  "Junior Engineer", "Engineering Technician", "Drafting Technician", "CAD Technician",
  "Architect", "Landscape Architect", "Interior Designer", "Urban Planner",
  "Architectural Designer", "Building Inspector", "Construction Manager",
  "Project Manager", "Site Supervisor", "Construction Foreman",

  // Manufacturing & Production
  "Production Manager", "Manufacturing Manager", "Plant Manager", "Operations Manager",
  "Quality Control Inspector", "Quality Assurance Manager", "Production Supervisor",
  "Assembly Line Worker", "Machine Operator", "Equipment Operator", "Forklift Operator",
  "Warehouse Worker", "Inventory Specialist", "Materials Handler", "Shipping Clerk",
  "Receiving Clerk", "Production Planner", "Production Scheduler", "Supply Chain Manager",
  "Logistics Manager", "Logistics Coordinator", "Distribution Manager", "Procurement Manager",
  "Purchasing Agent", "Buyer", "Vendor Manager", "Materials Manager", "Inventory Manager",
  "Warehouse Manager", "Facilities Manager", "Maintenance Manager", "Maintenance Technician",
  "Industrial Mechanic", "Electrician", "Millwright", "Welder", "Machinist",
  "Tool and Die Maker", "CNC Operator", "Production Worker", "Factory Worker",
  "Assembly Worker", "Packaging Worker", "Safety Manager", "Environmental Health and Safety Manager",
  "Lean Manufacturing Specialist", "Process Improvement Specialist", "Six Sigma Black Belt",

  // Transportation & Logistics
  "Truck Driver", "Delivery Driver", "Bus Driver", "Taxi Driver", "Uber Driver",
  "Lyft Driver", "Commercial Pilot", "Airline Pilot", "Flight Attendant", "Air Traffic Controller",
  "Aircraft Mechanic", "Airport Ground Crew", "Baggage Handler", "Ship Captain",
  "Marine Engineer", "Deckhand", "Port Worker", "Crane Operator", "Train Engineer",
  "Conductor", "Subway Operator", "Transit Operator", "Dispatcher", "Freight Coordinator",
  "Transportation Manager", "Fleet Manager", "Route Planner", "Traffic Analyst",
  "Customs Broker", "Freight Forwarder", "Supply Chain Analyst", "Import/Export Specialist",

  // Hospitality & Tourism
  "Hotel Manager", "Assistant Hotel Manager", "Front Desk Manager", "Front Desk Clerk",
  "Concierge", "Bellhop", "Housekeeper", "Housekeeping Supervisor", "Maintenance Worker",
  "Hotel Security", "Event Coordinator", "Banquet Manager", "Catering Manager",
  "Restaurant Manager", "Assistant Restaurant Manager", "Food Service Manager",
  "Chef", "Executive Chef", "Sous Chef", "Line Cook", "Prep Cook", "Kitchen Manager",
  "Server", "Waiter", "Waitress", "Bartender", "Host", "Hostess", "Busser",
  "Food Runner", "Dishwasher", "Barista", "Sommelier", "Pastry Chef", "Baker",
  "Caterer", "Food Truck Owner", "Restaurant Owner", "Travel Agent", "Tour Guide",
  "Travel Coordinator", "Vacation Planner", "Cruise Director", "Resort Manager",
  "Guest Services Manager", "Recreation Director", "Activities Coordinator",
  "Spa Manager", "Massage Therapist", "Esthetician", "Fitness Instructor",
  "Personal Trainer", "Lifeguard", "Ski Instructor", "Dive Instructor",

  // Construction & Trades
  "Construction Worker", "General Contractor", "Subcontractor", "Construction Supervisor",
  "Construction Foreman", "Project Manager", "Estimator", "Construction Estimator",
  "Carpenter", "Electrician", "Plumber", "HVAC Technician", "Heating and Cooling Technician",
  "Roofer", "Painter", "Drywall Installer", "Flooring Installer", "Tile Installer",
  "Concrete Worker", "Mason", "Bricklayer", "Stonemason", "Glazier", "Insulation Worker",
  "Demolition Worker", "Heavy Equipment Operator", "Crane Operator", "Excavator Operator",
  "Bulldozer Operator", "Backhoe Operator", "Road Construction Worker", "Bridge Builder",
  "Ironworker", "Steelworker", "Structural Iron Worker", "Sheet Metal Worker",
  "Pipefitter", "Steamfitter", "Boilermaker", "Elevator Installer", "Solar Panel Installer",
  "Wind Turbine Technician", "Telecommunications Installer", "Cable Installer",
  "Alarm Installer", "Security System Installer", "Home Inspector", "Building Inspector",
  "Code Enforcement Officer", "Surveyor", "Land Surveyor",

  // Retail & Customer Service
  "Retail Sales Associate", "Cashier", "Store Manager", "Assistant Store Manager",
  "Department Manager", "Shift Supervisor", "Team Leader", "Stock Clerk", "Inventory Associate",
  "Merchandiser", "Visual Merchandiser", "Loss Prevention Specialist", "Security Guard",
  "Customer Service Representative", "Customer Service Manager", "Call Center Agent",
  "Call Center Supervisor", "Technical Support Representative", "Help Desk Technician",
  "Customer Success Specialist", "Client Services Representative", "Account Coordinator",
  "Sales Floor Associate", "Fitting Room Attendant", "Jewelry Sales Associate",
  "Electronics Sales Associate", "Automotive Sales Associate", "Real Estate Agent",
  "Real Estate Broker", "Property Manager", "Leasing Agent", "Mortgage Loan Officer",
  "Insurance Sales Agent", "Insurance Broker", "Claims Representative", "Claims Adjuster",

  // Arts, Media & Entertainment
  "Actor", "Actress", "Director", "Producer", "Screenwriter", "Cinematographer",
  "Film Editor", "Sound Engineer", "Lighting Technician", "Camera Operator",
  "Photographer", "Videographer", "Video Editor", "Graphic Designer", "Web Designer",
  "Animator", "3D Artist", "VFX Artist", "Game Designer", "Game Developer",
  "Game Programmer", "Level Designer", "Character Artist", "Concept Artist",
  "Illustrator", "Comic Book Artist", "Fashion Designer", "Textile Designer",
  "Jewelry Designer", "Industrial Designer", "Product Designer", "Set Designer",
  "Costume Designer", "Makeup Artist", "Hair Stylist", "Model", "Fashion Model",
  "Musician", "Singer", "Songwriter", "Music Producer", "Audio Engineer",
  "Sound Technician", "DJ", "Radio Host", "Podcast Host", "Voice Actor",
  "Narrator", "News Anchor", "Reporter", "Journalist", "Writer", "Author",
  "Editor", "Copy Editor", "Proofreader", "Content Writer", "Technical Writer",
  "Blogger", "Social Media Influencer", "YouTuber", "Streamer", "Content Creator",
  "Art Director", "Creative Director", "Brand Designer", "Marketing Designer",
  "UX Writer", "Grant Writer", "Speechwriter", "Translator", "Interpreter",
  "Librarian", "Archivist", "Museum Curator", "Art Curator", "Gallery Manager",
  "Event Planner", "Wedding Planner", "Party Planner", "Concert Promoter",
  "Talent Agent", "Casting Director", "Theatre Manager", "Box Office Manager",

  // Science & Research
  "Research Scientist", "Laboratory Scientist", "Clinical Research Scientist", "Biomedical Scientist",
  "Biotechnology Scientist", "Pharmaceutical Scientist", "Chemist", "Biochemist",
  "Microbiologist", "Molecular Biologist", "Cell Biologist", "Marine Biologist",
  "Wildlife Biologist", "Environmental Scientist", "Geologist", "Meteorologist",
  "Astronomer", "Astrophysicist", "Physicist", "Nuclear Physicist", "Materials Scientist",
  "Food Scientist", "Agricultural Scientist", "Soil Scientist", "Plant Scientist",
  "Animal Scientist", "Veterinary Scientist", "Forensic Scientist", "Crime Lab Analyst",
  "Research Assistant", "Laboratory Technician", "Research Coordinator", "Clinical Research Coordinator",
  "Data Scientist", "Statistician", "Epidemiologist", "Public Health Researcher",
  "Market Research Analyst", "Survey Researcher", "Social Science Researcher",
  "Psychology Researcher", "Anthropologist", "Archaeologist", "Historian",
  "Political Scientist", "Economist", "Sociologist", "Linguist", "Mathematician",

  // Government & Public Service
  "City Manager", "Mayor", "Council Member", "Government Administrator", "Policy Analyst",
  "Legislative Assistant", "Congressional Aide", "Diplomat", "Foreign Service Officer",
  "Embassy Staff", "Immigration Officer", "Customs Officer", "Border Patrol Agent",
  "Park Ranger", "Forest Ranger", "Game Warden", "Environmental Inspector",
  "Health Inspector", "Building Inspector", "Fire Inspector", "Safety Inspector",
  "Tax Examiner", "Revenue Agent", "IRS Agent", "Postal Worker", "Mail Carrier",
  "Postal Clerk", "DMV Clerk", "Court Clerk", "City Clerk", "County Clerk",
  "Social Services Worker", "Child Protective Services Worker", "Eligibility Worker",
  "Public Health Officer", "Emergency Management Coordinator", "Disaster Relief Coordinator",
  "Veterans Affairs Counselor", "Military Recruiter", "Intelligence Analyst",
  "Government Accountant", "Budget Analyst", "Public Relations Specialist",
  "Communications Director", "Press Secretary", "Lobbyist", "Political Consultant",
  "Campaign Manager", "Fundraiser", "Grant Administrator", "Program Administrator",

  // Military & Defense
  "Soldier", "Marine", "Sailor", "Airman", "Officer", "Enlisted Personnel",
  "Military Police", "Combat Engineer", "Military Intelligence Officer", "Pilot",
  "Navigator", "Flight Engineer", "Mechanic", "Communications Specialist",
  "Medic", "Military Nurse", "Military Doctor", "Chaplain", "Judge Advocate",
  "Supply Specialist", "Logistics Specialist", "Administrative Specialist",
  "Human Resources Specialist", "Financial Management Specialist", "Cybersecurity Specialist",
  "Information Technology Specialist", "Radar Operator", "Air Traffic Controller",
  "Weapons Specialist", "Explosive Ordnance Disposal Specialist", "Special Forces",
  "Navy SEAL", "Army Ranger", "Marine Raider", "Air Force Pararescue",
  "Military Contractor", "Defense Contractor", "Security Clearance Specialist",
  "Military Trainer", "Drill Sergeant", "Military Recruiter", "Veterans Counselor",

  // Energy & Utilities
  "Power Plant Operator", "Nuclear Power Plant Operator", "Electrical Power Line Installer",
  "Electrical Lineman", "Utility Worker", "Gas Utility Worker", "Water Treatment Plant Operator",
  "Wastewater Treatment Plant Operator", "Water Quality Technician", "Meter Reader",
  "Utility Technician", "Renewable Energy Technician", "Solar Panel Installer",
  "Wind Turbine Technician", "Hydroelectric Plant Operator", "Energy Auditor",
  "Energy Analyst", "Environmental Compliance Specialist", "Pipeline Operator",
  "Oil Rig Worker", "Petroleum Engineer", "Mining Engineer", "Geologist",
  "Environmental Engineer", "Sustainability Coordinator", "Energy Manager",
  "Utilities Manager", "Power Systems Engineer", "Electrical Engineer",
  "Mechanical Engineer", "Chemical Engineer", "Nuclear Engineer",

  // Agriculture & Food Production
  "Farmer", "Rancher", "Agricultural Worker", "Farm Manager", "Ranch Manager",
  "Crop Specialist", "Livestock Specialist", "Dairy Farmer", "Poultry Farmer",
  "Fish Farmer", "Aquaculture Specialist", "Agricultural Inspector", "Food Inspector",
  "Veterinarian", "Animal Nutritionist", "Agricultural Engineer", "Irrigation Specialist",
  "Pest Control Specialist", "Agricultural Sales Representative", "Seed Sales Representative",
  "Equipment Operator", "Tractor Operator", "Combine Operator", "Farm Hand",
  "Greenhouse Worker", "Nursery Worker", "Landscaper", "Groundskeeper",
  "Tree Trimmer", "Arborist", "Horticulturist", "Plant Breeder", "Soil Scientist",
  "Food Scientist", "Food Technologist", "Quality Control Inspector", "Food Safety Inspector",
  "Agricultural Economist", "Farm Business Advisor", "Agricultural Extension Agent",
  "Rural Development Specialist", "Cooperative Extension Agent", "4-H Agent",

  // Skilled Trades & Technical
  "Mechanic", "Auto Mechanic", "Diesel Mechanic", "Aircraft Mechanic", "Motorcycle Mechanic",
  "Heavy Equipment Mechanic", "Small Engine Mechanic", "Marine Mechanic", "Bicycle Mechanic",
  "Automotive Technician", "Transmission Specialist", "Brake Specialist", "Tire Technician",
  "Auto Body Repair Technician", "Paint Technician", "Glass Installer", "Locksmith",
  "Appliance Repair Technician", "Computer Repair Technician", "Electronics Technician",
  "Cell Phone Repair Technician", "Watch Repair Technician", "Jewelry Repair Specialist",
  "Tailor", "Seamstress", "Alterations Specialist", "Upholsterer", "Furniture Maker",
  "Cabinet Maker", "Woodworker", "Carpenter", "Finish Carpenter", "Framing Carpenter",
  "Cabinetmaker", "Furniture Refinisher", "Antique Restorer", "Clock Repair Specialist",
  "Musical Instrument Repair Technician", "Piano Tuner", "Gunsmith", "Blacksmith",
  "Metalworker", "Welder", "Fabricator", "Sheet Metal Worker", "Machinist",
  "Tool and Die Maker", "Precision Machinist", "CNC Machinist", "Mold Maker",

  // Personal Care & Services
  "Hair Stylist", "Barber", "Cosmetologist", "Nail Technician", "Esthetician",
  "Massage Therapist", "Personal Trainer", "Fitness Instructor", "Yoga Instructor",
  "Pilates Instructor", "Dance Instructor", "Swimming Instructor", "Martial Arts Instructor",
  "Life Coach", "Personal Shopper", "Image Consultant", "Wedding Planner",
  "Event Planner", "Party Planner", "Caterer", "Personal Chef", "Private Chef",
  "Housekeeper", "Cleaning Service Worker", "Maid", "Janitor", "Custodian",
  "Groundskeeper", "Landscaper", "Gardener", "Pool Cleaner", "Window Cleaner",
  "Carpet Cleaner", "Pest Control Technician", "Exterminator", "Handyman",
  "Home Repair Specialist", "Property Maintenance Worker", "Building Maintenance Worker",
  "Apartment Maintenance Technician", "Superintendent", "Building Manager",
  "Property Manager", "Real Estate Property Manager", "Facility Manager",
  "Security Guard", "Private Security Officer", "Bodyguard", "Private Investigator",
  "Process Server", "Courier", "Delivery Driver", "Moving Company Worker",
  "Pet Groomer", "Dog Walker", "Pet Sitter", "Animal Trainer", "Dog Trainer",
  "Childcare Worker", "Nanny", "Babysitter", "Au Pair", "Tutor", "Elder Care Worker",
  "Home Health Aide", "Personal Care Aide", "Companion", "Caregiver",

  // Non-Profit & Social Services
  "Social Worker", "Case Worker", "Family Therapist", "Substance Abuse Counselor",
  "Mental Health Counselor", "Marriage Counselor", "School Counselor", "Career Counselor",
  "Rehabilitation Counselor", "Victim Advocate", "Community Outreach Coordinator",
  "Program Coordinator", "Program Manager", "Executive Director", "Development Director",
  "Fundraising Coordinator", "Grant Writer", "Volunteer Coordinator", "Event Coordinator",
  "Public Relations Coordinator", "Communications Coordinator", "Marketing Coordinator",
  "Development Associate", "Program Assistant", "Administrative Assistant",
  "Youth Worker", "Community Center Director", "Homeless Shelter Manager",
  "Food Bank Coordinator", "Soup Kitchen Manager", "Disaster Relief Worker",
  "Red Cross Worker", "Peace Corps Volunteer", "Missionary", "Religious Leader",
  "Pastor", "Priest", "Rabbi", "Imam", "Minister", "Chaplain", "Youth Pastor",
  "Music Director", "Church Administrator", "Religious Education Director",

  // Sports & Recreation
  "Professional Athlete", "Coach", "Assistant Coach", "Athletic Trainer", "Sports Medicine Doctor",
  "Physical Therapist", "Strength and Conditioning Coach", "Personal Trainer",
  "Fitness Instructor", "Group Fitness Instructor", "Yoga Instructor", "Pilates Instructor",
  "Swimming Instructor", "Tennis Instructor", "Golf Instructor", "Ski Instructor",
  "Snowboard Instructor", "Martial Arts Instructor", "Dance Instructor", "Gymnastics Instructor",
  "Sports Broadcaster", "Sports Journalist", "Sports Writer", "Sports Photographer",
  "Sports Videographer", "Sports Commentator", "Sports Analyst", "Scout", "Talent Scout",
  "Recruiter", "Athletic Director", "Recreation Director", "Program Director",
  "Facility Manager", "Stadium Manager", "Arena Manager", "Equipment Manager",
  "Groundskeeper", "Maintenance Worker", "Concessions Worker", "Ticket Sales Representative",
  "Box Office Manager", "Event Coordinator", "Marketing Manager", "Sponsorship Coordinator",
  "Sports Agent", "Sports Marketing Specialist", "Fan Experience Coordinator",
  "Sports Psychologist", "Nutritionist", "Dietitian", "Massage Therapist",
  "Lifeguard", "Pool Manager", "Recreation Center Manager", "Summer Camp Director",
  "Summer Camp Counselor", "Outdoor Education Instructor", "Adventure Guide",
  "Tour Guide", "Park Ranger", "Wilderness Guide", "Fishing Guide", "Hunting Guide",

  // Specialized & Unique Professions
  "Actuary", "Statistician", "Market Research Analyst", "Survey Researcher",
  "Operations Research Analyst", "Management Analyst", "Business Consultant",
  "IT Consultant", "Financial Consultant", "HR Consultant", "Marketing Consultant",
  "Strategy Consultant", "Process Improvement Consultant", "Change Management Consultant",
  "Organizational Development Consultant", "Training Consultant", "Technology Consultant",
  "Cybersecurity Consultant", "Environmental Consultant", "Engineering Consultant",
  "Legal Consultant", "Healthcare Consultant", "Education Consultant", "Real Estate Consultant",
  "Investment Consultant", "Tax Consultant", "Risk Management Consultant",
  "Compliance Consultant", "Quality Assurance Consultant", "Safety Consultant",
  "Ergonomics Specialist", "User Experience Researcher", "Market Researcher",
  "Consumer Insights Analyst", "Trend Analyst", "Competitive Intelligence Analyst",
  "Business Intelligence Analyst", "Data Analyst", "Reporting Analyst", "Financial Analyst",
  "Budget Analyst", "Cost Analyst", "Pricing Analyst", "Revenue Analyst",
  "Performance Analyst", "Quality Analyst", "Systems Analyst", "Process Analyst",
  "Workflow Analyst", "Efficiency Expert", "Productivity Specialist", "Lean Specialist",
  "Six Sigma Specialist", "Continuous Improvement Specialist", "Innovation Manager",
  "R&D Manager", "Product Development Manager", "New Product Development Specialist",
  "Technology Transfer Specialist", "Patent Agent", "Trademark Specialist",
  "Intellectual Property Specialist", "Licensing Specialist", "Contract Negotiator",
  "Procurement Specialist", "Vendor Relations Manager", "Supplier Quality Engineer",
  "Quality Systems Manager", "Regulatory Affairs Specialist", "Clinical Affairs Manager",
  "Medical Affairs Manager", "Drug Safety Specialist", "Pharmacovigilance Specialist",
  "Clinical Data Manager", "Biostatistician", "Medical Writer", "Regulatory Writer",
  "Technical Editor", "Scientific Writer", "Grant Writer", "Proposal Writer",
  "Content Strategist", "SEO Specialist", "Digital Marketing Specialist",
  "Social Media Strategist", "Community Manager", "Brand Manager", "Product Manager",
  "Program Manager", "Project Coordinator", "Scrum Master", "Agile Coach",
  "Change Management Specialist", "Training Specialist", "Learning and Development Specialist",
  "Organizational Development Specialist", "Talent Acquisition Specialist", "Recruiter",
  "Headhunter", "Executive Recruiter", "HR Generalist", "HR Specialist", "HR Manager",
  "Compensation Analyst", "Benefits Administrator", "Payroll Specialist", "HRIS Specialist",
  "Employee Relations Specialist", "Diversity and Inclusion Specialist", "Workplace Safety Specialist",
  "Environmental Health and Safety Manager", "Risk Manager", "Insurance Specialist",
  "Claims Specialist", "Loss Control Specialist", "Safety Engineer", "Industrial Hygienist",
  "Occupational Health Nurse", "Workers' Compensation Specialist", "Disability Case Manager",
  "Ergonomist", "Human Factors Engineer", "Usability Engineer", "UX Researcher",
  "User Researcher", "Design Researcher", "Market Research Moderator", "Focus Group Moderator",
  "Survey Designer", "Questionnaire Designer", "Data Collection Specialist", "Field Researcher",
  "Ethnographer", "Cultural Anthropologist", "Sociologist", "Political Scientist",
  "Economist", "Demographer", "Urban Planner", "Transportation Planner", "Environmental Planner",
  "Land Use Planner", "Community Planner", "Regional Planner", "Historic Preservationist",
  "Archaeological Technician", "Museum Technician", "Collections Manager", "Registrar",
  "Conservation Specialist", "Art Conservator", "Book Conservator", "Paper Conservator",
  "Textile Conservator", "Paintings Conservator", "Sculpture Conservator", "Archaeological Conservator",
];

export const LOCATIONS = [
  // Africa
  { value: "algeria", label: "Algeria" },
  { value: "angola", label: "Angola" },
  { value: "benin", label: "Benin" },
  { value: "botswana", label: "Botswana" },
  { value: "burkina-faso", label: "Burkina Faso" },
  { value: "burundi", label: "Burundi" },
  { value: "cabo-verde", label: "Cabo Verde" },
  { value: "cameroon", label: "Cameroon" },
  { value: "central-african-republic", label: "Central African Republic" },
  { value: "chad", label: "Chad" },
  { value: "comoros", label: "Comoros" },
  { value: "congo-brazzaville", label: "Congo (Brazzaville)" },
  { value: "congo-kinshasa", label: "Congo (Kinshasa)" },
  { value: "cote-divoire", label: "Côte d'Ivoire" },
  { value: "djibouti", label: "Djibouti" },
  { value: "egypt", label: "Egypt" },
  { value: "equatorial-guinea", label: "Equatorial Guinea" },
  { value: "eritrea", label: "Eritrea" },
  { value: "eswatini", label: "Eswatini" },
  { value: "ethiopia", label: "Ethiopia" },
  { value: "gabon", label: "Gabon" },
  { value: "gambia", label: "Gambia" },
  { value: "ghana", label: "Ghana" },
  { value: "guinea", label: "Guinea" },
  { value: "guinea-bissau", label: "Guinea-Bissau" },
  { value: "kenya", label: "Kenya" },
  { value: "lesotho", label: "Lesotho" },
  { value: "liberia", label: "Liberia" },
  { value: "libya", label: "Libya" },
  { value: "madagascar", label: "Madagascar" },
  { value: "malawi", label: "Malawi" },
  { value: "mali", label: "Mali" },
  { value: "mauritania", label: "Mauritania" },
  { value: "mauritius", label: "Mauritius" },
  { value: "morocco", label: "Morocco" },
  { value: "mozambique", label: "Mozambique" },
  { value: "namibia", label: "Namibia" },
  { value: "niger", label: "Niger" },
  { value: "nigeria", label: "Nigeria" },
  { value: "rwanda", label: "Rwanda" },
  { value: "sao-tome-and-principe", label: "São Tomé and Príncipe" },
  { value: "senegal", label: "Senegal" },
  { value: "seychelles", label: "Seychelles" },
  { value: "sierra-leone", label: "Sierra Leone" },
  { value: "somalia", label: "Somalia" },
  { value: "south-africa", label: "South Africa" },
  { value: "south-sudan", label: "South Sudan" },
  { value: "sudan", label: "Sudan" },
  { value: "tanzania", label: "Tanzania" },
  { value: "togo", label: "Togo" },
  { value: "tunisia", label: "Tunisia" },
  { value: "uganda", label: "Uganda" },
  { value: "zambia", label: "Zambia" },
  { value: "zimbabwe", label: "Zimbabwe" },

  // Asia
  { value: "afghanistan", label: "Afghanistan" },
  { value: "armenia", label: "Armenia" },
  { value: "azerbaijan", label: "Azerbaijan" },
  { value: "bahrain", label: "Bahrain" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "bhutan", label: "Bhutan" },
  { value: "brunei", label: "Brunei" },
  { value: "cambodia", label: "Cambodia" },
  { value: "china", label: "China" },
  { value: "cyprus", label: "Cyprus" },
  { value: "georgia", label: "Georgia" },
  { value: "india", label: "India" },
  { value: "indonesia", label: "Indonesia" },
  { value: "iran", label: "Iran" },
  { value: "iraq", label: "Iraq" },
  { value: "israel", label: "Israel" },
  { value: "japan", label: "Japan" },
  { value: "jordan", label: "Jordan" },
  { value: "kazakhstan", label: "Kazakhstan" },
  { value: "kuwait", label: "Kuwait" },
  { value: "kyrgyzstan", label: "Kyrgyzstan" },
  { value: "laos", label: "Laos" },
  { value: "lebanon", label: "Lebanon" },
  { value: "malaysia", label: "Malaysia" },
  { value: "maldives", label: "Maldives" },
  { value: "mongolia", label: "Mongolia" },
  { value: "myanmar", label: "Myanmar" },
  { value: "nepal", label: "Nepal" },
  { value: "north-korea", label: "North Korea" },
  { value: "oman", label: "Oman" },
  { value: "pakistan", label: "Pakistan" },
  { value: "palestine", label: "Palestine" },
  { value: "philippines", label: "Philippines" },
  { value: "qatar", label: "Qatar" },
  { value: "saudi-arabia", label: "Saudi Arabia" },
  { value: "singapore", label: "Singapore" },
  { value: "south-korea", label: "South Korea" },
  { value: "sri-lanka", label: "Sri Lanka" },
  { value: "syria", label: "Syria" },
  { value: "tajikistan", label: "Tajikistan" },
  { value: "thailand", label: "Thailand" },
  { value: "timor-leste", label: "Timor-Leste" },
  { value: "turkey", label: "Turkey" },
  { value: "turkmenistan", label: "Turkmenistan" },
  { value: "uae", label: "United Arab Emirates" },
  { value: "uzbekistan", label: "Uzbekistan" },
  { value: "vietnam", label: "Vietnam" },
  { value: "yemen", label: "Yemen" },

  // Europe
  { value: "albania", label: "Albania" },
  { value: "andorra", label: "Andorra" },
  { value: "austria", label: "Austria" },
  { value: "belarus", label: "Belarus" },
  { value: "belgium", label: "Belgium" },
  { value: "bosnia-herzegovina", label: "Bosnia and Herzegovina" },
  { value: "bulgaria", label: "Bulgaria" },
  { value: "croatia", label: "Croatia" },
  { value: "czech-republic", label: "Czech Republic" },
  { value: "denmark", label: "Denmark" },
  { value: "estonia", label: "Estonia" },
  { value: "finland", label: "Finland" },
  { value: "france", label: "France" },
  { value: "germany", label: "Germany" },
  { value: "greece", label: "Greece" },
  { value: "hungary", label: "Hungary" },
  { value: "iceland", label: "Iceland" },
  { value: "ireland", label: "Ireland" },
  { value: "italy", label: "Italy" },
  { value: "kosovo", label: "Kosovo" },
  { value: "latvia", label: "Latvia" },
  { value: "liechtenstein", label: "Liechtenstein" },
  { value: "lithuania", label: "Lithuania" },
  { value: "luxembourg", label: "Luxembourg" },
  { value: "malta", label: "Malta" },
  { value: "moldova", label: "Moldova" },
  { value: "monaco", label: "Monaco" },
  { value: "montenegro", label: "Montenegro" },
  { value: "netherlands", label: "Netherlands" },
  { value: "north-macedonia", label: "North Macedonia" },
  { value: "norway", label: "Norway" },
  { value: "poland", label: "Poland" },
  { value: "portugal", label: "Portugal" },
  { value: "romania", label: "Romania" },
  { value: "russia", label: "Russia" },
  { value: "san-marino", label: "San Marino" },
  { value: "serbia", label: "Serbia" },
  { value: "slovakia", label: "Slovakia" },
  { value: "slovenia", label: "Slovenia" },
  { value: "spain", label: "Spain" },
  { value: "sweden", label: "Sweden" },
  { value: "switzerland", label: "Switzerland" },
  { value: "ukraine", label: "Ukraine" },
  { value: "united-kingdom", label: "United Kingdom" },
  { value: "vatican-city", label: "Vatican City" },

  // North America
  { value: "antigua-barbuda", label: "Antigua and Barbuda" },
  { value: "bahamas", label: "Bahamas" },
  { value: "barbados", label: "Barbados" },
  { value: "belize", label: "Belize" },
  { value: "canada", label: "Canada" },
  { value: "costa-rica", label: "Costa Rica" },
  { value: "cuba", label: "Cuba" },
  { value: "dominica", label: "Dominica" },
  { value: "dominican-republic", label: "Dominican Republic" },
  { value: "el-salvador", label: "El Salvador" },
  { value: "grenada", label: "Grenada" },
  { value: "guatemala", label: "Guatemala" },
  { value: "haiti", label: "Haiti" },
  { value: "honduras", label: "Honduras" },
  { value: "jamaica", label: "Jamaica" },
  { value: "mexico", label: "Mexico" },
  { value: "nicaragua", label: "Nicaragua" },
  { value: "panama", label: "Panama" },
  { value: "saint-kitts-nevis", label: "Saint Kitts and Nevis" },
  { value: "saint-lucia", label: "Saint Lucia" },
  { value: "saint-vincent-grenadines", label: "Saint Vincent and the Grenadines" },
  { value: "trinidad-tobago", label: "Trinidad and Tobago" },
  { value: "united-states", label: "United States" },

  // South America
  { value: "argentina", label: "Argentina" },
  { value: "bolivia", label: "Bolivia" },
  { value: "brazil", label: "Brazil" },
  { value: "chile", label: "Chile" },
  { value: "colombia", label: "Colombia" },
  { value: "ecuador", label: "Ecuador" },
  { value: "guyana", label: "Guyana" },
  { value: "paraguay", label: "Paraguay" },
  { value: "peru", label: "Peru" },
  { value: "suriname", label: "Suriname" },
  { value: "uruguay", label: "Uruguay" },
  { value: "venezuela", label: "Venezuela" },

  // Oceania
  { value: "australia", label: "Australia" },
  { value: "fiji", label: "Fiji" },
  { value: "kiribati", label: "Kiribati" },
  { value: "marshall-islands", label: "Marshall Islands" },
  { value: "micronesia", label: "Micronesia" },
  { value: "nauru", label: "Nauru" },
  { value: "new-zealand", label: "New Zealand" },
  { value: "palau", label: "Palau" },
  { value: "papua-new-guinea", label: "Papua New Guinea" },
  { value: "samoa", label: "Samoa" },
  { value: "solomon-islands", label: "Solomon Islands" },
  { value: "tonga", label: "Tonga" },
  { value: "tuvalu", label: "Tuvalu" },
  { value: "vanuatu", label: "Vanuatu" },
];

// Themes
export const THEMES = {
  LIGHT: "light",
  DARK: "dark",
  SYSTEM: "system",
};

// Notification Types
export const NOTIFICATION_TYPES = {
  SUCCESS: "success",
  ERROR: "error",
  WARNING: "warning",
  INFO: "info",
};
